<?
	Yii::app()->clientScript->registerCoreScript('jquery');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Hukumonline English</title>
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		<meta name="google-site-verification" content="MUDP2J4JyyfKSWJsjfuglidOXiHOU_vn5VLXY7S-G8w" />
		<link rel="stylesheet" type="text/css" media="all" href="<?echo Yii::app()->theme->baseUrl;?>/css/elastic.css" />
		<script src="<?echo Yii::app()->theme->baseUrl;?>/css/elastic.js" type="text/javascript" language="javascript" charset="utf-8"></script>
		<link rel="stylesheet" type="text/css" media="screen" href="<?echo Yii::app()->theme->baseUrl;?>/css/typography3.css" />
		
		<link href="<?echo Yii::app()->baseUrl;?>/js/lightbox/facebox/facebox.css" media="screen" rel="stylesheet" type="text/css"/>
		<script src="<?echo Yii::app()->baseUrl;?>/js/lightbox/facebox/facebox.js" type="text/javascript"></script>
		<script src="<?echo Yii::app()->baseUrl;?>/js/slider/jquery.cycle/jquery.cycle.all.min.js" type="text/javascript"></script>
		
		<link rel="stylesheet" type="text/css" media="screen" href="<?echo Yii::app()->theme->baseUrl;?>/css/superfish/css/superfish.css" /> 
		<script type="text/javascript" src="<?echo Yii::app()->theme->baseUrl;?>/css/superfish/js/superfish.js"></script> 
		<script type="text/javascript"> 

		    $(document).ready(function(){ 
		        $("ul.sf-menu").superfish(); 
		    }); 
			
			jQuery(document).ready(function($) {
			  $('a[rel*=facebox]').facebox()
			})
			
			

		</script>
		
		<!-- Generated by OpenX 2.8.5 -->
		
	</head>
	<body>
		<?php include(Yii::app()->theme->basePath.'/views/layouts/analytics.php');?>
		
		<?php $this->widget('hole.components.HeaderMenu'); ?>
		
		<div style="padding-top:5px"></div>
		<?php include(Yii::app()->theme->basePath.'/views/layouts/subheader.php');?>
		
		<div style="padding-top:10px"></div>
		<div class="unit horizontal-center layout on-3 columns">
			<div class="fixed column" style="width:260px;">
				<div class="container" style="padding:0 5px 0 5px">
					<div style="padding-top:0px"></div>
					<?php $this->widget('hole.components.LatestCatalog', array(
						'folderGuid' => 'lt481074ef14e7a',
						'limit' => 2, 'title'=>'Indonesian Legal News', 'showLongDescription'=>0
					)); ?>
					<?php $this->widget('hole.components.LatestCatalog', array(
						'folderGuid' => 'lt481074ef14e7a', 'offset'=>2,
						'limit' => 8, 'title'=>'More News', 'showLongDescription'=>-1, 'showTitle'=>0
					)); ?>
				</div>
			</div>
			<div class="fixed column" style="width:430px;">
				<div class="container" style="padding:0 5px 0 5px">
					<?php $this->widget('hole.components.NewsSlider'); ?>
					<div style="padding-top:10px;_padding-top:55px"></div>
					<div class="container" style="border:1px solid #999999;background:#ffffcb;padding-left:10px;padding-right:10px;">
						<?php $this->widget('hole.components.LatestCatalog', array(
							'folderGuid' => 'lt47f05d1f9b110', 'offset'=>0,
							'limit' => 5, 'title'=>'Indonesian Legal Brief', 'showAltTitle'=>1,'showLongDescription'=>-1
						)); ?>
						<div style="padding-top:10px"></div>
						<?php $this->widget('hole.components.LatestCatalog', array(
							'folderGuid' => 'lt47f05c9c52db0', 'offset'=>0,
							'limit' => 3, 'title'=>'Indonesian Law Digest', 'showAltTitle'=>1,'showLongDescription'=>0
						)); ?>
					</div>
					<?php echo $content;?>
				</div>
			</div>
			<div class="fixed column" style="width:310px;">
				<div class="container" style="padding:0 5px 0 5px">
					<?php foreach($this->rightPortlets as $w)
					        $this->widget($w['class'],$w['properties']); ?>
					<div style="padding-top:10px"></div>
					<img src="<?echo Yii::app()->theme->baseUrl;?>/images/banner-right1.jpg" width="300px" >
				</div>
			</div>
		</div>	
			
		
		<div style="padding-top:10px"></div>
		
		<div class="unit horizontal-center layout on-3 columns">
			<div class="fixed column" style="width:260px;">
				<div class="container" style="padding:0 5px 0 5px">
					<a href="http://twitter.com/indolegalnews"><img src="<?echo Yii::app()->theme->baseUrl;?>/images/ban-250.jpg" style="padding-right:0px"></a>
					<div style="padding-top:5px"></div>
					<a href="/pages/tag/lt47f05d1f9b110"><img src="<?echo Yii::app()->theme->baseUrl;?>/images/ban.120.a.jpg" width="120px" style="padding-right:5px"></a>
					<a href="/pages/tag/lt47f05c9c52db0"><img src="<?echo Yii::app()->theme->baseUrl;?>/images/ban.120.b.jpg" width="120px" style="padding-right:0px"></a>
				</div>
			</div>
			<div class="fixed column" style="width:430px;">
				<div class="container" style="padding:0 5px 0 5px">
					<?php $this->widget('hole.components.LatestCatalogByKeyword', array(
						'folderGuid' => 'lt481074ef14e7a', 'offset'=>0,
						'limit' => 3, 'title'=>'@Hukumonline', 'showLongDescription'=>0
					)); ?>
				</div>
			</div>
			<div class="fixed column" style="width:310px;">
				<div class="container" style="padding:0 5px 0 5px">
					<script src="http://widgets.twimg.com/j/2/widget.js"></script>
					<script>
					new TWTR.Widget({
					  version: 2,
					  type: 'profile',
					  rpp: 5,
					  interval: 6000,
					  width: 'auto',
					  height: 300,
					  theme: {
					    shell: {
					      background: '#939699',
					      color: '#030303'
					    },
					    tweets: {
					      background: '#ffffff',
					      color: '#000000',
					      links: '#4aed05'
					    }
					  },
					  features: {
					    scrollbar: false,
					    loop: false,
					    live: false,
					    hashtags: true,
					    timestamp: true,
					    avatars: false,
					    behavior: 'all'
					  }
					}).render().setUser('indolegalnews').start();
					</script>
				</div>
			</div>
		</div>
		
		<div style="padding-top:10px"></div>
		<?php include(Yii::app()->theme->basePath.'/views/layouts/footer.php');?>
	</body>
</html>